### ISSUE TITLE
No Permissions

### ISSUE THREAD

**Issue by NillerMedDild** [Elrol/Server-Utilities#11]
I just made a new creative world, and Server Utilities disallows me from using commands. I'm using default configs.

`Server Utils-1.14.4-0.9.2`

**Comment by Elrol** [comment]
Will test this out asap.

**Comment by Elrol** [comment]
I am able to use the default permissions, are you not able to use any permissions, or just the op perms?
I can throw some code in to deal with this, If you use a server, the console should be able to run all commands (unless you need to be a player) but on single player there is none. Give me a bit and I will make a build to fix this.

**Comment by Elrol** [comment]
In the most recent build (v0.9.3) I added a bypass for permissions only for the owner of the single player worlds. I had it set up to check if the player was in creative also, but once I changed to survival I could not do much else to change them, so I just enabled it for the world owner. If you dont want players, on single player, to have access too all of the commands then let me know, I will see about changing it over to something a bit better. Sorry that it took so long, I went out for dinner for an hour or so after seeing this issue.

**Comment by NillerMedDild** [comment]
No worries, I don't think it took long for you to fix it at all.

I would prefer that singleplayer world owners only have access to OP commands if they have cheats enabled, so players who want to play without cheats enabled can do so - Is that the case now?

**Comment by Elrol** [comment]
Currently it just checks if the player is the owner of the single player world. I will add the next check in a bit and you can expect that in the next build.

**Comment by Elrol** [comment]
Ok, added the extra check to see if the player is the owner, and that the world is in cheatmode. It seems to be working, I am thinking that I will hold off on pushing another build for a few days unless a bug shows up.

**Comment by NillerMedDild** [comment]
Alright, thank you :) One last thing, and I hope this isn't coming off as nagging, but have you taken Open to LAN Enable cheats mode into account?

**Comment by Elrol** [comment]
It should be, but I have not been able to test this as of yet.

**Comment by Elrol** [comment]
It currently does not allow players other then the owner to have op, but thats an easy fix.
I will have a build to push here shorty as I did find a small issue that was fixed.

**Comment by Elrol** [comment]
Making the build now, then hitting the sack. This build also will have beta kits enabled, as well as giving gamemode its original numeral system in addition to the new one, but if you have any issues with the new version, possibly with kits, lemme know asap :D

**Comment by Elrol** [comment]
its been approved, v0.9.4

**Comment by NillerMedDild** [comment]
Thank you, good work :D
