### ISSUE TITLE
Command "/function" not working on default rank

### ISSUE THREAD

**Issue by felixmegion** [Elrol/Server-Utilities#18]
Version 1.16.1-1.3.15

Even though default.json has the following permissions, I cannot run any function commands from datapacks.

-     "command.function",
-     "command.function.name",
-     "command.reload"

Has this been fixed in a newer version?

**Comment by Elrol** [comment]
Did you check if the permissions are in the permission.json inside of the
config folder?

The plugin goes through and finds any command that is registered, makes a
permission for it, and saves it there
I will try to take a look at this sometime here soon regardless

**Comment by felixmegion** [comment]
I found the issue. My player needed to be manually OPed before the permissions checking starts to kick in.

I'm not sure if this part of the mod works correctly.

> The way this was done was by making all players op level, or permission level 4, and then upon a command execution checking if there is a permission set for that command.
