### ISSUE TITLE
mod not saving home locations

### ISSUE THREAD

**Issue by kreezxil** [Elrol/Server-Utilities#3]
probably not saving warps either, but we don't use those.

When I update the mod in the pack on the server, and restart the server, the homes every one had set are all gone.

we have world saving turned on.

**Comment by Elrol** [comment]
hmm can you post the logs, and which version is it? I will run some tests on my end and see what I can come up with.

**Comment by Elrol** [comment]
So when testing, I am unable to recreate this. The server info is stored inside of the world directory, inside the data folder and in the file called serverdata.dat

On top of that, between the versions i have not touched the serverdata file and it should still be the same as it was in the first version. Is it possible that you deleted the world when updating?

**Comment by kreezxil** [comment]
i don't delete my server worlds when updating

I players with colonies all over the place, they would be highly upset if I
were doing that.

**Comment by kreezxil** [comment]
I found the issue and it's how you're doing paths. You need to use a path builder and not hard coded windows paths. What you wrote works fine on a windows server but fails on linux server because path branch indicator goes the other way, you use a backslash, linux uses a forward slash.

```
[16:20:41] [Server thread/INFO] [co.gi.el.El.Main/]: [ServerUtils]: Data file: /home/kreezxil/work/mcgs/./world/data\serverdata.dat
```
this is why my players aren't getting their homes back when i restart the server.

The following links will help you discover what you need to fix this

https://stackoverflow.com/questions/3548775/platform-independent-paths-in-java
https://www.sghill.net/how-do-i-make-cross-platform-file-paths-in-java.html

**Comment by kreezxil** [comment]
The lines that need to be fixed are at:

https://github.com/Elrol/Server-Utilities/blob/master/src/main/java/com/github/elrol/ElrolsUtilities/libs/JsonMethods.java#L24

https://github.com/Elrol/Server-Utilities/blob/master/src/main/java/com/github/elrol/ElrolsUtilities/libs/JsonMethods.java#L34

and

https://github.com/Elrol/Server-Utilities/blob/master/src/main/java/com/github/elrol/ElrolsUtilities/libs/JsonMethods.java#L40

**Comment by kreezxil** [comment]
lol, ironically you use the universal path at L40. changing the others to use that should fix that problem.

**Comment by kreezxil** [comment]
Here's the **Ma Essentials** server tools doing the same thing, they use the universal file separator "/" from Linux.

https://github.com/Maciej916/Ma-Essentials/blob/master/src/main/java/com/maciej916/maessentials/config/Config.java#L107-L113

That will be your only change you need to make to fix my issue.

Also I'm switching your mod for that one, I needed to have this resolved yesterday.

You get yours fixed and i'll put it in the 1.14.4 Colonial Age pack.

I suggest adding as many bukkit/sponge style commands as you can to your mod so as to compete with **Ma Essentials**

**Comment by Elrol** [comment]
Thats the plan, to add as many commands as possible, I will have this fixed tonight and will push it asap. Thanks for that.

**Comment by Elrol** [comment]
Ok, in the alpha build (0.5.0) I fixed the issue, and also added permissions to all of the commands and added a permission command. It is on curseforge, and just needs a bit of testing before I call it beta, I have not tested it much, other then to make sure that it seemed to work.

**Comment by kreezxil** [comment]
I'll put it in  colonial age and begin testing it there.

**Comment by Elrol** [comment]
Sounds good, I am currently rewriting a bit of the code to allow for translations while I add the /tpa and /tphere commands and what not

**Comment by kreezxil** [comment]
I can think of a ton of commands back from when I ran bukkit. Having them
in your mod would likely catapult you to fame above the other server tools.
Especially if the only argument one gives is a target.

Like
/smite <player> - hits a player with lightning bolt, aka charged creeper
style
/bomb <player> - spawns primed tnt at a player's location
/heal <player> - restores player hearts
/feed <player> - restores player food saturation
/flood <player> - spawns water around a player

granted some of those are for harassment or a way to punish annoying players

**Comment by Elrol** [comment]
Added permissions and ranks, as well as tpa commands. I will work on more commands as the week progresses, and make a few of the current commands work a bit better.
