### ISSUE TITLE
0.6.0

### ISSUE THREAD

**Issue by kreezxil** [Elrol/Server-Utilities#4]
Is installed in World of Dragons - A New Age and should start getting loads of downloads as a result of that.

There are numerous issues with such as the lang file not operating.

and the odd error such as when using /back or /home it shoots back err.delay-running

**Comment by Elrol** [comment]
Very odd, I will take a look right now. err.delay-running should only fire when the player has a command already in cooldown, but I will see.

**Comment by Elrol** [comment]
Ok, just downloaded the mod, and ran it on a forge 28.1.1 server, everything seems to be working ok. I will update my test server and see if that is the issue. I have not had anyone to test with on a multiplayer server so it has just been me on the test server so there may be some issues with multiple players using commands. I will see about getting some people to help test after I update my server.

**Comment by Elrol** [comment]
I am not sure what would cause the localizations not to load, the only thing is that a client that tried joining the server did not have the mod or the resource pack (either works for clients) but I will play the pack for a bit and see

**Comment by Elrol** [comment]
This should be fixed in the recent release
