### ISSUE TITLE
Cant log into Server

### ISSUE THREAD

**Issue by IchigoGames** [Elrol/Server-Utilities#6]
the issue of not being able to log in on server is still a issue with mod i can connect the first time after server restart but then the next time i try to connect it wont let me but i can after disabling this mod,

mc 1.14.4
Forge 28.1.79
Elrols Utilities-1.14.4-0.8.1

**Comment by Elrol** [comment]
Can you provide the log that you have? I will take a look at what the issue could be.

**Comment by Elrol** [comment]
It may be the same issue that was described in another issue: https://github.com/Elrol/Server-Utilities/issues/7

If that is the issue you were having, please try the new build that I just uploaded. If not, supply the logs so that I can fix them

**Comment by IchigoGames** [comment]
yes one sec

**Comment by IchigoGames** [comment]
https://www.dropbox.com/s/zno2pi9kckpyjjk/logs.zip?dl=0

**Comment by IchigoGames** [comment]
nvm it looks like its fixed after updating
