### ISSUE TITLE
Consistent Naming

### ISSUE THREAD

**Issue by NillerMedDild** [Elrol/Server-Utilities#9]
Hello!

I'd really like if the modname, mod jar name and config files had the same (or very similar) names. Configs are server utils, CurseForge name is Elrol's Server Utilities and the modname is Elrols Utility.

Though I'd prefer if they were all called Elrols Server Utilities, I'd be perfectly happy if they all just stick to the same name :)

**Comment by Elrol** [comment]
Honestly yeah, that has been bugging me too, it was kind of a test to see which name i thought sounded better. The change will be with the next update.

**Comment by NillerMedDild** [comment]
Thank you :)

**Comment by Elrol** [comment]
Update released that fixes the teleports between dimensions, and renamed the project to match. ServerUtils, easier to say then Elrol's Server Utilities XD

**Comment by NillerMedDild** [comment]
Awesome :D
